name: hskd
version: git
summary: A Handshake implementation for miners, wallets, and exchanges
description: |
  HSKD is an implementation of the Handshake Protocol.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  hskd:
    command: hskd
    plugs: [network, network-bind]

parts:
  hskd:
    source: .
    plugin: nodejs
    build-packages: [python, gcc]
    node-engine: 7.9.0
