name: Docs
on:
  release:
    types: [published]
jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install -g jsdoc
        jsdoc -c jsdoc.json
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/reference